# Generated by Django 5.1.7 on 2025-03-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='employee',
        ),
        migrations.AlterField(
            model_name='client',
            name='service_type',
            field=models.ManyToManyField(to='clients.service'),
        ),
    ]
