# Generated by Django 5.1.7 on 2025-03-15 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_workerserviceshare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerserviceshare',
            name='fixed_amount',
        ),
        migrations.RemoveField(
            model_name='workerserviceshare',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='workerserviceshare',
            name='share_type',
        ),
        migrations.RemoveField(
            model_name='workerserviceshare',
            name='service',
        ),
        migrations.CreateModel(
            name='WorkerServiceShareDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_type', models.CharField(choices=[('percentage', 'Процент'), ('fixed', 'Фиксированная сумма')], default='percentage', max_length=10)),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.service')),
                ('worker_service_share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.workerserviceshare')),
            ],
        ),
        migrations.AddField(
            model_name='workerserviceshare',
            name='service',
            field=models.ManyToManyField(through='clients.WorkerServiceShareDetail', to='clients.service'),
        ),
    ]
