# Generated by Django 5.1.7 on 2025-03-16 20:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_remove_workerserviceshare_fixed_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('rent', 'Аренда'), ('salary', 'Зарплата'), ('supplies', 'Закупки'), ('other', 'Другое')], max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
